### PR TITLE
Handling multi-space characters (Japanese, Chinese...) width better

### PR DESCRIPTION
**Pull request by Elvyria**
Continuing [#530](https://github.com/sayanarijit/xplr/pull/530), i added `visual_cursor` method as discussed, but currently fighting incorrect display at scroll position.

Currently I'm not sure if code in example is to blame or [tui-rs](https://github.com/fdehau/tui-rs). Investigating.

### CODE REVIEW

**Comment by sayanarijit** [comment]
Thank you. If possible, Please post some characters for testing, I'll review soon.

**Comment by Elvyria** [comment]
Sure
JP: `ビルドワールドIII〈上〉埋もれた遺跡`
KR: `로맨틱 만화, 만화 아니메, 한국 만화`

**Comment by Elvyria** [comment]
Alright, example should work now much better. I tested it for quite a bit, with mixed languages, and I didn't see any anomalies.

**Comment by sayanarijit** [comment]
I have taken your changes in https://github.com/sayanarijit/tui-input/pull/15

**Pull request closed without merging**
